# Generated by Django 4.2.20 on 2025-04-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecureFileTransfer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('filename', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
